from tkinter import * 
import time 
#----------------------------------------->buttons
def addstudent():
    addroot= Toplevel(master=entry_frame)
    addroot.title("Student management system")
    addroot.grab_set()
    addroot.geometry('470x470+220+200')
    addroot.config(bg='gray25')
    addroot.resizable(False,False)
    idlabel= Label(addroot,text='Enter Id',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    idlabel.place(x=10,y=10)
    nameval=StringVar()
    mobileval=StringVar()
    emailval=StringVar()
    addressval=StringVar()
    genderval=StringVar()
    idval=StringVar()
    identry=Entry(addroot,font=('chiller',20,'bold'),bd=5,textvariable=idval,width=13)
    identry.place(x=250,y=10)
    namelabel= Label(addroot,text='Enter Name',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    namelabel.place(x=10,y=70)
    nameentry=Entry(addroot,font=('chiller',20,'bold'),bd=5,textvariable=nameval,width=13)
    nameentry.place(x=250,y=70)
    emaillabel= Label(addroot,text='Enter E-mail',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    emaillabel.place(x=10,y=130)
    emailentry=Entry(addroot,font=('chiller',20,'bold'),bd=5,textvariable=emailval,width=13)
    emailentry.place(x=250,y=130)
    mobilelabel= Label(addroot,text='Enter Mobile No',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    mobilelabel.place(x=10,y=190)
    mobileentry=Entry(addroot,font=('chiller',20,'bold'),bd=5,textvariable=mobileval,width=13)
    mobileentry.place(x=250,y=190)
    genderlabel= Label(addroot,text='Enter Gender',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    genderlabel.place(x=10,y=250)
    genderentry=Entry(addroot,font=('chiller',20,'bold'),bd=5,textvariable=genderval,width=13)
    genderentry.place(x=250,y=250)
    addresslabel= Label(addroot,text='Enter Address',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    addresslabel.place(x=10,y=310)
    addressentry=Entry(addroot,font=('chiller',20,'bold'),bd=5,textvariable=addressval,width=13)
    addressentry.place(x=250,y=310)
    submit=Button(addroot,text="Submit",width=18,font=('times', 14,'bold'),relief=RIDGE,borderwidth=5,bg='red',activebackground='LightYellow2')
    submit.place(x=10,y=390)
    addroot.mainloop()
def search():
    searchroot= Toplevel(master=entry_frame)
    searchroot.title("Student management system")
    searchroot.grab_set()
    searchroot.geometry('470x470+220+200')
    searchroot.config(bg='gray25')
    searchroot.resizable(False,False)
    idlabel= Label(searchroot,text='Enter Id',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    idlabel.place(x=10,y=10)
    nameval=StringVar()
    mobileval=StringVar()
    emailval=StringVar()
    addressval=StringVar()
    genderval=StringVar()
    idval=StringVar()
    identry=Entry(searchroot,font=('chiller',20,'bold'),bd=5,textvariable=idval,width=13)
    identry.place(x=250,y=10)
    namelabel= Label(searchroot,text='Enter Name',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    namelabel.place(x=10,y=70)
    nameentry=Entry(searchroot,font=('chiller',20,'bold'),bd=5,textvariable=nameval,width=13)
    nameentry.place(x=250,y=70)
    emaillabel= Label(searchroot,text='Enter E-mail',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    emaillabel.place(x=10,y=130)
    emailentry=Entry(searchroot,font=('chiller',20,'bold'),bd=5,textvariable=emailval,width=13)
    emailentry.place(x=250,y=130)
    mobilelabel= Label(searchroot,text='Enter Mobile No',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    mobilelabel.place(x=10,y=190)
    mobileentry=Entry(searchroot,font=('chiller',20,'bold'),bd=5,textvariable=mobileval,width=13)
    mobileentry.place(x=250,y=190)
    genderlabel= Label(searchroot,text='Enter Gender',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    genderlabel.place(x=10,y=250)
    genderentry=Entry(searchroot,font=('chiller',20,'bold'),bd=5,textvariable=genderval,width=13)
    genderentry.place(x=250,y=250)
    addresslabel= Label(searchroot,text='Enter Address',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    addresslabel.place(x=10,y=310)
    addressentry=Entry(searchroot,font=('chiller',20,'bold'),bd=5,textvariable=addressval,width=13)
    addressentry.place(x=250,y=310)
    submit=Button(searchroot,text="Submit",width=18,font=('times', 14,'bold'),relief=RIDGE,borderwidth=5,bg='red',activebackground='LightYellow2')
    submit.place(x=10,y=390)
    searchroot.mainloop()
def delete():
    deleteroot=Toplevel(master=entry_frame)
    deleteroot.title("Student management system")
    deleteroot.grab_set()
    deleteroot.geometry('470x470+220+200')
    deleteroot.config(bg='gray25')
    deleteroot.resizable(False,False)
    idlabel= Label(deleteroot,text='Enter Id',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    idlabel.place(x=10,y=10)
    nameval=StringVar()
    mobileval=StringVar()
    emailval=StringVar()
    addressval=StringVar()
    genderval=StringVar()
    idval=StringVar()
    identry=Entry(deleteroot,font=('chiller',20,'bold'),bd=5,textvariable=idval,width=13)
    identry.place(x=250,y=10)
    namelabel= Label(deleteroot,text='Enter Name',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    namelabel.place(x=10,y=70)
    nameentry=Entry(deleteroot,font=('chiller',20,'bold'),bd=5,textvariable=nameval,width=13)
    nameentry.place(x=250,y=70)
    emaillabel= Label(deleteroot,text='Enter E-mail',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    emaillabel.place(x=10,y=130)
    emailentry=Entry(deleteroot,font=('chiller',20,'bold'),bd=5,textvariable=emailval,width=13)
    emailentry.place(x=250,y=130)
    mobilelabel= Label(deleteroot,text='Enter Mobile No',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    mobilelabel.place(x=10,y=190)
    mobileentry=Entry(deleteroot,font=('chiller',20,'bold'),bd=5,textvariable=mobileval,width=13)
    mobileentry.place(x=250,y=190)
    genderlabel= Label(deleteroot,text='Enter Gender',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    genderlabel.place(x=10,y=250)
    genderentry=Entry(deleteroot,font=('chiller',20,'bold'),bd=5,textvariable=genderval,width=13)
    genderentry.place(x=250,y=250)
    addresslabel= Label(deleteroot,text='Enter Address',bg='coral1',font=('chiller',20,'bold'),relief=GROOVE,borderwidth=3,width=20)
    addresslabel.place(x=10,y=310)
    addressentry=Entry(deleteroot,font=('chiller',20,'bold'),bd=5,textvariable=addressval,width=13)
    addressentry.place(x=250,y=310)
    submit=Button(deleteroot,text="Submit",width=18,font=('times', 14,'bold'),relief=RIDGE,borderwidth=5,bg='red',activebackground='LightYellow2')
    submit.place(x=10,y=390)
    deleteroot.mainloop()

#----------------------------------------->connect to database
def connectdb():
    dbroot= Toplevel()
    dbroot.geometry('470x250')
    dbroot.grab_set()
    dbroot.resizable(False,False)
    dbroot.config(bg='plum1')
    #------------------------------------------>labels
    hostlabel1=Label(dbroot,text="Enter the Host",bg='OliveDrab1',font=("Times New Roman", 12, "italic"),relief=GROOVE,borderwidth=3,width=12,anchor='w')
    hostlabel1.place(x=10,y=10)
    userlabel1=Label(dbroot,text="Enter the User",bg='OliveDrab1',font=("Times New Roman", 12, "italic"),relief=GROOVE,borderwidth=3,width=12,anchor='w')
    userlabel1.place(x=10,y=70)
    passwordlabel1=Label(dbroot,text="Enter the Password",bg='OliveDrab1',font=("Times New Roman", 12, "italic"),relief=GROOVE,borderwidth=3,width=15,anchor='w')
    passwordlabel1.place(x=10,y=130)
    #---------------------------------------------------->Entry boxes
    hostval=StringVar()
    userval=StringVar()
    passwordval=StringVar()
    hostentry=Entry(dbroot,width=20,borderwidth=3,font=("Times New Roman", 12, "italic"),relief=GROOVE,bd=5)
    hostentry.place(x=150,y=10)
    userentry=Entry(dbroot,width=20,borderwidth=3,font=("Times New Roman", 12, "italic"),relief=GROOVE,bd=5)
    userentry.place(x=150,y=70)
    passwordentry=Entry(dbroot,width=20,borderwidth=3,font=("Times New Roman", 12, "italic"),relief=GROOVE,bd=5)
    passwordentry.place(x=159,y=130)
    dbroot.mainloop()

def tik():
    timestring=time.strftime("%H:%M:%S")
    datestring=time.strftime("%d-%m-%y")
    clock.config(text=f"Time: {timestring}\nDate: {datestring}")
    clock.after(200,tik)
root=Tk()
root.title("Student Management")
root.configure(bg='#90ee90')
root.geometry('1174x640+200+50')
root.resizable(False,False)
#--------------------------------------------------------------------->Data entry frame
entry_frame=Frame(root,bg='seashell3',relief=GROOVE,borderwidth=5)
entry_frame.place(x=10,y=80,width=400,height=400)
frontlabel= Label(entry_frame,text="MANAGEMENT",bg='seashell3',font=("chiller", 20, "italic bold"),width=25)
frontlabel.pack(side=TOP,expand=True)
addbtn=Button(entry_frame,text=' Add Student',width=25,font=("Times New Roman", 12, "italic"),bd=6,activebackground='seashell4',command=addstudent)
addbtn.pack(side=TOP,expand=True)
searchbtn=Button(entry_frame,text=' Search Student',width=25,font=("Times New Roman", 12, "italic"),bd=6,activebackground='seashell4',command=addstudent)
searchbtn.pack(side=TOP,expand=True)
deletebtn=Button(entry_frame,text=' Delete Student',width=25,font=("Times New Roman", 12, "italic"),bd=6,activebackground='seashell4',command=addstudent)
deletebtn.pack(side=TOP,expand=True)
showDataFrame = Frame(root,bg='seashell3',relief=GROOVE,borderwidth=5)
showDataFrame.place(x=550,y=80,width=600,height=400)
#--------------------------------------------------------------------------->slides
ss='Student Management'
slide1 = Label(root, text=ss, font=('Arial', 9), bg='seaGreen3',relief=GROOVE,borderwidth=5)
slide1.place(x=10, y=10, width=150, height=50)
clock=Label(root, font=('times', 14,'bold'), bg='azure',relief=RIDGE,borderwidth=5)
clock.place(x=1020,y=6,width=150,height=70)
tik()
connectbutton=Button(root,text="Connect to database",width=23,font=('times', 14,'bold'),relief=RIDGE,borderwidth=5,bg='gold4',activebackground='LightYellow2',command=connectdb)
connectbutton.place(x=10,y=580,width=400,height=50)
#--------------------------------------------------------------------------->submit button
submitbutton=Button(root,text="Submit",width=23,font=('times', 14,'bold'),relief=RIDGE,borderwidth=5,bg='red',activebackground='LightYellow2')
submitbutton.place(x=890,y=580)
root.mainloop()
